environment:
  matrix:
    - nodejs_version: '12'

version: '{build}'

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - yarn --version
  - yarn install

test_script:
  - yarn test
  - yarn run cov:send
  - yarn run cov:check

build: off
deploy: off
